services:
  shareit-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shareit-server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data  # Для сохранения базы H2 на диске
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/shareit
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update